# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/natkham/Desktop/cs184/projects/p4-clothsim-natkham/CGL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/natkham/Desktop/cs184/projects/p4-clothsim-natkham/CGL/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.14.1/share/cmake/Modules/FindFreetype.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.14.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.14.1/share/cmake/Modules/FindPackageMessage.cmake))

/Users/natkham/Desktop/cs184/projects/p4-clothsim-natkham/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.14.1/bin/cmake -H/Users/natkham/Desktop/cs184/projects/p4-clothsim-natkham -B/Users/natkham/Desktop/cs184/projects/p4-clothsim-natkham/xcode
